[package]
name = "a_ni_me"
version = "0.1.0"
description = "Manage your animes in one place"
authors = ["Waradu"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.71"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "lib"]

[build-dependencies]
tauri-build = { version = "2.0.0-rc.10", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "2.0.0-rc.11", features = [] }
tauri-plugin-sql = { version = "2.0.0-beta.0", features = ["sqlite"] }
